routes/web.php
<?php

Route::get('noPermission', 'DashboardController@noPermission')->name('noPermission');

Route::post('register', 'Auth\RegisterController@register');

Route::get('register', 'HomeController@register')->name('register');

Route::get('frontend', 'HomeController@index');

/* Tenant Routes */
Route::group(array(
    'domain' => '{subdomain}.' . env('HOST_NAME'),
    'as' => 'tenant.',
    'middleware' => 'multisubdomain'
), (function () {

    /* Auth Routes*/
    Route::get('/', [
        'as' => 'landing',
        'uses' => 'LoginController@getTenantLogin'
    ]);

    Route::post('/login', [
        'as' => 'login',
        'uses' => 'LoginController@tenantLogin'
    ]);

    Route::group(['middleware' => ['authen.tenant']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@tenantLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@dashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me.edit',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::put('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::put('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        /* My Tenant */

        Route::get('tenants/me', [
            'as' => 'tenants.me',
            'uses' => 'TenantController@me'
        ]);

        Route::get('tenants/me/edit', [
            'as' => 'tenants.me.edit',
            'uses' => 'TenantController@meEdit'
        ]);

        Route::get('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpertPage',
            'uses' => 'TenantController@selectExpertPage'
        ]);

        Route::post('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpert',
            'uses' => 'TenantController@selectExpert'
        ]);

        Route::post('tenants/{id}/unselect-expert', [
            'as' => 'tenants.unselectExpert',
            'uses' => 'TenantController@unselectExpert'
        ]);

        /* End My Tenant */

        Route::resource('tenants', 'tenant\TenantController');

        Route::resource('categories', 'tenant\CategoryController');

        Route::resource('sub_categories', 'tenant\SubCategoryController');

        Route::resource('users', 'tenant\UserController');

        Route::resource('roles', 'tenant\RoleController');

        Route::resource('sections', 'tenant\SectionController');

        Route::post('courses/{id}/section', [
            'as' => 'courses.add.section',
            'uses' => 'SectionController@store'
        ]);

        Route::resource('courses', 'tenant\CourseController');

        Route::get('users/role/{id}', [
            'as' => 'users.role',
            'uses' => 'UserController@usersByRole'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::post('users/select-expert', 'UserController@selectExpert')->name('users.selectExpert');

        Route::delete('sections/delete-all/{id}', [
            'as' => 'sections.delete.all',
            'uses' => 'SectionController@deleteAll'
        ]);

        Route::post('material/store', 'MaterialController@postMaterial');

        Route::delete('material/delete/{id}', 'MaterialController@deleteMaterial');

        Route::resource('quizzes', 'QuizController');

    });
    /* End Auth Routes*/

}));
/* end Tenant Routes */

Route::group(array('domain' => '{domain}'), (function () {

    Route::get('/', [
        'as' => '/',
        'uses' => 'LoginController@getLogin',
        'middleware' => 'multidomain'
    ]);

    Route::post('login', [
        'as' => 'login',
        'uses' => 'LoginController@postLogin'
    ]);

    Route::group(['middleware' => ['authen']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@getLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@dashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me.edit',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::put('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::put('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        /* My Tenant */

        Route::get('tenants/me', [
            'as' => 'tenants.me',
            'uses' => 'TenantController@me'
        ]);

        Route::get('tenants/me/edit', [
            'as' => 'tenants.me.edit',
            'uses' => 'TenantController@meEdit'
        ]);

        Route::get('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpertPage',
            'uses' => 'TenantController@selectExpertPage'
        ]);

        Route::post('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpert',
            'uses' => 'TenantController@selectExpert'
        ]);

        Route::post('tenants/{id}/unselect-expert', [
            'as' => 'tenants.unselectExpert',
            'uses' => 'TenantController@unselectExpert'
        ]);

        /* End My Tenant */

        Route::resource('tenants', 'TenantController');

        Route::resource('categories', 'CategoryController');

        Route::resource('sub_categories', 'SubCategoryController');

        Route::resource('users', 'UserController');

        Route::resource('roles', 'RoleController');

        Route::resource('sections', 'SectionController');

        Route::post('courses/{id}/section', [
            'as' => 'courses.add.section',
            'uses' => 'SectionController@store'
        ]);

        Route::resource('courses', 'CourseController');

        Route::get('users/role/{id}', [
            'as' => 'users.role',
            'uses' => 'UserController@usersByRole'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::post('users/select-expert', 'UserController@selectExpert')->name('users.selectExpert');

        Route::delete('sections/delete-all/{id}', [
            'as' => 'sections.delete.all',
            'uses' => 'SectionController@deleteAll'
        ]);

        Route::post('material/store', 'MaterialController@postMaterial');

        Route::delete('material/delete/{id}', 'MaterialController@deleteMaterial');

        Route::resource('quizzes', 'QuizController');

        // Route::post('quiz/store', 'QuizController@store');


        /* Append File */
//        Route::get('bangke', 'CategoryController@index');
        /* End Append File */
    });

}));


Route::get('/home', 'HomeController@index')->name('home');

Route::post('/users/add-role', 'UserController@addRole');

Route::post('/users/delete-role', 'UserController@deleteRole');

Route::get('404', [
    'as' => 'notfound',
    'uses' => 'HomeController@notfound'
]);

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

     protected $hidden = [
         'password', 'remember_token',
     ];

    public function roles()
    {
      return $this->belongsToMany('App\Role', 'user_roles');
    }

    public function role(){
        return $this->hasOne('App\Role', 'id', 'role_id');
    }

    public function tenant(){
        return $this->hasOne('App\Tenant', 'id', 'tenant_id');
    }

    private function checkIfUserHasRole($need_role){
      // return (strtolower($need_role)==strtolower($this->role->name)) ? true : null;
    }

    public function hasRole($roles){
      if (is_array($roles)) {
        foreach ($roles as $need_role) {
          if ($this->checkIfUserHasRole($need_role)) {
            return true;
          }
        }
      } else {
        return $this->checkIfUserHasRole($roles);
      }
      return false;
    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use Auth;
use Illuminate\Support\Facades\Hash;
use Log;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function checkAuth($domain, Request $request)
    {
        $credentials = [
            'email' => $request->email,
            'password' => $request->password,
        ];

        if (!Auth::attempt($credentials)) {
            return response('Username or password is wrong!', 403);
        }

        return response(Auth::user(), 201);
    }

    public function index($domain)
    {
        $users = User::all();
        $roles = Role::all();

        return view('users.index')
            ->withUsers($users)
            ->withRoles($roles);
    }

    public function usersByRole($domain, $id)
    {
        $users = User::where('role_id', $id)->get();

        $roles = Role::all();

        return view('users.index')
            ->withUsers($users)
            ->withRoles($roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($domain)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store($domain, Request $request)
    {

        $tenant = Tenant::where(['domain' => $domain])->first();

        $this->validate($request, [
            'fullname' => 'required|max:255',
            'ktp_id' => 'required|unique:users',
            'username' => 'required|unique:users',
            'password' => 'required',
            'email' => 'required|unique:users',
            'phone' => 'required|unique:users',
        ]);

        $user = new User;

        $user->fullname = $request->fullname;
        $user->ktp_id = $request->ktp_id;
        $user->username = $request->username;
        $user->password = Hash::make($request->password);
        $user->email = $request->email;
        $user->birth_date = $request->birth_date;
        $user->phone = $request->phone;
        $user->mobile = $request->mobile;
        $user->mobile2 = $request->mobile2;
        $user->pin_bb = $request->pin_bb;
        $user->notes = $request->notes;

        $user->photo = $request->photo;

        $user->address = $request->address;
        $user->zipcode = $request->zipcode;
        $user->fb = $request->fb;
        $user->tw = $request->tw;
        $user->website = $request->website;
        $user->status = $request->status;
        $user->hobby = $request->hobby;
        $user->reason = $request->reason;

//        Default User Role
        $user->role_id = 5;

//        Default Tenant and Branch
        $user->branch_id = 0;
        $user->tenant_id = $tenant->id;

        $user->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($domain, $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($domain, $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update($domain, Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($domain, $id)
    {
        //
    }

    public function changeRole($domain, Request $request, $id)
    {
        $user = User::find($id);
        $user->role_id = $request->role_id;

        $user->save();

        return redirect()->back();
    }

    public function addRole($domain, Request $request)
    {
        $user = User::find($request->user_id);
        $user->roles()->attach($request->role_id);

        return response()->json($user->roles);
    }

    public function deleteRole($domain, Request $request)
    {
        $user = User::find($request->user_id);
        $user->roles()->detach($request->role_id);

        return response()->json($user->roles);
    }

    public function selectExpert($domain, Request $request)
    {
        $user = User::find($request->user_id);
        $user->tenant_id = $request->tenant_id;

        $user->save();

        return redirect()->back();
    }

}

app/Http/Controllers/tenant/UserController.php
<?php

namespace App\Http\Controllers\tenant;

use App\Role;
use App\Tenant;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($subdomain)
    {
        $tenant = Tenant::where('subdomain', $subdomain)->first();

        $users = User::where('tenant_id', $tenant->id)->get();

        $roles = Role::all();

        return view('users.index')
            ->withUsers($users)
            ->withRoles($roles);
    }

    public function usersByRole($subdomain, $role_id)
    {
        $tenant = Tenant::where('subdomain', $subdomain)->first();

        $users = User::where([
            ['role_id', '=', $role_id],
            ['tenant_id', '=', $tenant->id]
        ])->get();

        $roles = Role::all();

        return view('users.index')
            ->withUsers($users)
            ->withRoles($roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store($subdomain, Request $request)
    {
        $this->validate($request, [
            'fullname' => 'required|max:255',
            'ktp_id' => 'required|unique:users',
            'username' => 'required|unique:users',
            'password' => 'required',
            'email' => 'required|unique:users',
            'phone' => 'required|unique:users',
        ]);

        $tenant = Tenant::where('subdomain', $subdomain)->first();

        $user = new User;

        $user->fullname = $request->fullname;
        $user->ktp_id = $request->ktp_id;
        $user->username = $request->username;
        $user->password = Hash::make($request->password);
        $user->email = $request->email;
        $user->birth_date = $request->birth_date;
        $user->phone = $request->phone;
        $user->mobile = $request->mobile;
        $user->mobile2 = $request->mobile2;
        $user->pin_bb = $request->pin_bb;
        $user->notes = $request->notes;

        $user->photo = $request->photo;

        $user->address = $request->address;
        $user->zipcode = $request->zipcode;
        $user->fb = $request->fb;
        $user->tw = $request->tw;
        $user->website = $request->website;
        $user->status = $request->status;
        $user->hobby = $request->hobby;
        $user->reason = $request->reason;

//        Default User Role (Student)
        $user->role_id = 5;

//        Default Branch
        $user->branch_id = 0;

        Log::debug('Tenant ID = ' . $tenant->id);
        $user->tenant_id = $tenant->id;

        $user->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/index.blade.php
@extends('layouts.main')

@section('content')

    @php
        $tenant = App\Tenant::where(['domain' => $_SERVER['HTTP_HOST']])->first();
        $permission = App\Permission::where(['role_id' => Auth::user()->role['id'], 'tenant_id' => $tenant->id])->first();
    @endphp

    <div class="row">

        <div class="modal fade" id="modalAdd">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="defaultModalLabel">Tambah User</h4>
                    </div>

                    <form action="{{ Auth::user()->tenant->is_cname ? route('users.store', $_SERVER['HTTP_HOST']) : route('tenant.users.store', [$_SERVER['HTTP_HOST'], Auth::user()->tenant->subdomain]) }}"
                          method="post" data-parsley-validate>

                        <div class="modal-body">
                            <fieldset>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label> Foto : </label>
                                        <input type="file" name="company_logo">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Nama Lengkap : </label>
                                        <input type="text" name="fullname" class="form-control" required>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label> Nomot KTP : </label>
                                        <input type="number" name="ktp_id" class="form-control">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label> Username : </label>
                                        <input type="text" name="username" class="form-control" required>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label> E-mail : </label>
                                        <input type="email" name="email" class="form-control" required>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label> Kata Sandi: </label>
                                        <input type="password" name="password" class="form-control" required>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label> Telepon : </label>
                                        <input type="number" name="phone" class="form-control">
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label> Nomor Handphone 1 : </label>
                                        <input type="number" name="mobile" class="form-control">
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label> Nomor Handphone 2 : </label>
                                        <input type="number" name="mobile2" class="form-control">
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label> PIN BBM : </label>
                                        <input type="text" name="pin_bb" class="form-control">
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label> Kode Pos : </label>
                                        <input type="text" name="zipcode" class="form-control">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Alamat : </label>
                                        <textarea class="form-control" name="address" rows="3"></textarea>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Catatan : </label>
                                        <textarea class="form-control" name="notes" rows="3"></textarea>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Hobi : </label>
                                        <textarea class="form-control" name="hobby" rows="3"></textarea>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Alasan : </label>
                                        <textarea class="form-control" name="reason" rows="3"></textarea>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Facebook : </label>
                                        <input type="text" name="fb" class="form-control">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Twitter : </label>
                                        <input type="text" name="tw" class="form-control">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Website : </label>
                                        <input type="text" name="website" class="form-control">
                                    </div>
                                </div>

                            </fieldset>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                <i
                                        class="fa fa-close"></i>
                                Tutup
                            </button>
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-save"></i>
                                Simpan
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-xs-12">

            <div class="box box-primary">

                <div class="box-header">
                    <h3 class="box-title">Daftar User</h3>
                    <br>
                    <a class="btn btn-info pull-left col-md-1" href="#!" data-toggle="modal" data-target="#modalAdd">
                        <span class="fa fa-plus"></span>
                    </a>

                </div>

                <div class="box-body">
                    <table class="table js-basic-example dataTable">
                        <thead>
                        <tr>
                            <th>Nama</th>
                            <th>E-Mail</th>
                            <th>Peran</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($users as $user)
                            <tr>
                                <td>{{ $user->fullname }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    {!! Form::open(['route' => ['changeRole', $_SERVER['HTTP_HOST'], $user->id], 'method' => 'PUT', 'data-parsley-validate' => '', 'files' => true]) !!}
                                    <fieldset>

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <select class="form-control" name="role_id">
                                                    @foreach($roles as $role)
                                                        <option value="{{ $role->id }}" {{ $user->role->id === $role->id ? 'selected' : ''}}>{{ $role->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <button type="submit" class="btn btn-info">
                                                <i class="fa fa-refresh"></i>
                                            </button>
                                        </div>

                                    </fieldset>
                                    {!! Form::close() !!}
                                </td>

                                @if($permission->delete_user)
                                    <td class="text-right">
                                        <a href="#!" class="btn btn-danger btn-xs">
                                            <i class="fa fa-trash"></i>
                                            Hapus
                                        </a>
                                    </td>
                                @endif
                            </tr>
                        @endforeach

                        </tbody>
                    </table>

                </div>

            </div>

        </div>
    </div>

@endsection

@section('script')
    <script type="text/javascript">
        function addRole(user_id, role_id) {

            $.ajax({
                method: 'POST',
                url: '/users/add-role/',
                data: {
                    user_id: user_id,
                    role_id: role_id
                },
                async: true,
                success: function (response) {
                    var data = response;
                    console.log(data.length);
                    $("a#user" + user_id).append('sss');
                },
                error: function (data) {
                    console.log(data);
                    alert("fail" + ' ' + this.data)
                },
            });

        }

        function deleteRole(user_id, role_id) {

            // $.ajax({
            //   method: 'POST',
            //   url: '/users/delete-role/',
            //   data: {
            //     user_id: user_id,
            //     role_id: role_id
            //   },
            //   async: true,
            //   success: function(response){
            //       $("#" + role_id).remove();
            //   },
            //   error: function(data){
            //       console.log(data);
            //       alert("fail" + ' ' + this.data)
            //   },
            // });

        }
    </script>
@endsection