routes/web.php
<?php

Route::get('noPermission', 'DashboardController@noPermission')->name('noPermission');

Route::post('register', 'Auth\RegisterController@register');

Route::get('register', 'HomeController@register')->name('register');

Route::get('frontend', 'HomeController@index');

/* Tenant Routes */
Route::group(array(
    'domain' => '{subdomain}.' . env('HOST_NAME'),
    'as' => 'tenant.',
    'middleware' => 'multisubdomain'
), (function () {

    /* Auth Routes*/
    Route::get('/', [
        'as' => 'landing',
        'uses' => 'LoginController@getTenantLogin'
    ]);

    Route::post('login', [
        'as' => 'login',
        'uses' => 'LoginController@tenantLogin'
    ]);

    Route::group(['middleware' => ['authen.tenant']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@tenantLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@tenantDashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::put('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::put('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::resource('users', 'tenant\UserController');

        Route::resource('roles', 'RoleController');

        Route::resource('courses', 'CourseController');

    });
    /* End Auth Routes*/

}));
/* end Tenant Routes */

Route::group(array('domain' => '{domain}'), (function () {

    Route::get('/', [
        'as' => '/',
        'uses' => 'LoginController@getLogin',
        'middleware' => 'multidomain'
    ]);

    Route::post('login', [
        'as' => 'login',
        'uses' => 'LoginController@postLogin'
    ]);

    Route::group(['middleware' => ['authen']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@getLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@dashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me.edit',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::get('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::get('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        /* My Tenant */

        Route::get('tenants/me', [
            'as' => 'tenants.me',
            'uses' => 'TenantController@me'
        ]);

        Route::get('tenants/me/edit', [
            'as' => 'tenants.me.edit',
            'uses' => 'TenantController@meEdit'
        ]);

        Route::get('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpertPage',
            'uses' => 'TenantController@selectExpertPage'
        ]);

        Route::post('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpert',
            'uses' => 'TenantController@selectExpert'
        ]);

        Route::post('tenants/{id}/unselect-expert', [
            'as' => 'tenants.unselectExpert',
            'uses' => 'TenantController@unselectExpert'
        ]);

        /* End My Tenant */

        Route::resource('tenants', 'TenantController');

        Route::resource('categories', 'CategoryController');

        Route::resource('sub_categories', 'SubCategoryController');

        Route::resource('users', 'UserController');

        Route::resource('roles', 'RoleController');

        Route::resource('courses', 'CourseController');

        Route::get('users/role/{id}', [
            'as' => 'users.role',
            'uses' => 'UserController@usersByRole'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::post('users/select-expert', 'UserController@selectExpert')->name('users.selectExpert');

    });

}));


Route::get('/home', 'HomeController@index')->name('home');

Route::post('/users/add-role', 'UserController@addRole');

Route::post('/users/delete-role', 'UserController@deleteRole');

Route::get('404', [
    'as' => 'notfound',
    'uses' => 'HomeController@notfound'
]);

app/Tenant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tenant extends Model
{
    public function users()
    {
        return $this->hasMany('App\User');
    }

    public function courses()
    {
        return $this->hasMany('App\Course');
    }
}

app/Http/Controllers/TenantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use App\Tenant;
use App\User;
use Illuminate\Support\Facades\Log;
use Session;

class TenantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($domain)
    {
        $tenants = Tenant::all();
        return view('tenants.index')
            ->withTenants($tenants);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($domain)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store($domain, Request $request)
    {
//        Validate request
        if ((int)$request->is_cname === 1) {
            /* DOMAIN */
            $this->validate($request, [
                'name' => 'required|max:150|unique:tenants',
                'domain' => 'max:50|unique:tenants'
            ]);
        } else {
            /* SUBDOMAIN */
            $this->validate($request, [
                'name' => 'required|max:150|unique:tenants',
                'subdomain' => 'max:10|unique:tenants'
            ]);
        }

//        Save Tenant to database
        $tenant = new Tenant;
        $tenant->name = $request->name;
        $tenant->description = $request->description;

        if ((int)$request->is_cname === 1) {
            $tenant->domain = $request->domain;
            $tenant->subdomain = null;
        } else {
            $tenant->domain = null;
            $tenant->subdomain = $request->subdomain;
        }

        $tenant->is_cname = (int)$request->is_cname;
        $tenant->company_logo = "wowowowowo";
        $tenant->author_id = Auth::id();

        $tenant->save();

//        add success message with session flash (hanya untuk 1 page)
        Session::flash('success', 'Tenant berhasil di tambahkan !');

//        refresh the page
        return redirect()->back();
    }

    public function show($domain, $id)
    {
        $tenant = Tenant::find($id);

        $users = User::all();

        return view('tenants.detail')
            ->withTenant($tenant)
            ->withUsers($users);
    }

    public function me($domain)
    {
        $tenant = Tenant::where(['domain' => $domain])->first();

        $users = User::where(['tenant_id' => $tenant->id])->get();

        return view('tenants.me')
            ->withTenant($tenant)
            ->withUsers($users);
    }

    public function selectExpertPage($domain, $id)
    {
        $tenant = Tenant::find($id);

        $users = User::where(['tenant_id' => 1])->get();

        $experts = User::where(['role_id' => 3, 'tenant_id' => $tenant->id])->get();

        return view('tenants.selectexpert')
            ->withTenant($tenant)
            ->withUsers($users)
            ->withExperts($experts)
            ->withId($id);
    }

    public function selectExpert($domain, $id, Request $request)
    {

        $user = User::find($request->user_id);

        $user->tenant_id = $id;
        $user->role_id = 3;

        $user->save();

        return redirect()->back();
    }

    public function unselectExpert($domain, $id, Request $request)
    {

        $user = User::find($request->user_id);

        $user->tenant_id = 1;
        $user->role_id = 5;

        $user->save();

        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($domain, $id)
    {
        $tenant = Tenant::find($id);

        return view('tenants.edit')
            ->withTenant($tenant);
    }

    public function meEdit($domain)
    {
        $tenant = Tenant::where(['domain' => $domain])->first();

        return view('tenants.meedit')
            ->withTenant($tenant);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update($domain, Request $request, $id)
    {
        //        Validate request
        if ((int)$request->is_cname === 1) {
            /* DOMAIN */
            $this->validate($request, [
                'name' => 'required|max:150|unique:tenants,name,' . $id,
                'domain' => 'max:50|unique:tenants,domain,' . $id
            ]);
        } else {
            /* SUBDOMAIN */
            $this->validate($request, [
                'name' => 'required|max:150|unique:tenants,name,' . $id,
                'subdomain' => 'max:10|unique:tenants,subdomain,' . $id
            ]);
        }

//        Save Tenant to database
        $tenant = Tenant::find($id);
        Log::debug($tenant);
        $tenant->name = $request->name;
        $tenant->description = $request->description;

        if ((int)$request->is_cname === 1) {
            $tenant->domain = $request->domain;
            $tenant->subdomain = null;
        } else {
            $tenant->domain = null;
            $tenant->subdomain = $request->subdomain;
        }

        $tenant->is_cname = (int)$request->is_cname;
        $tenant->company_logo = "wowowowowo";
        $tenant->author_id = Auth::id();

        $tenant->save();

//        add success message with session flash (hanya untuk 1 page)
        Session::flash('success', 'Tenant berhasil di edit !');

//        refresh the page
        return redirect()->route('tenants.index', $domain);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tenant = Tenant::find($id);

//        if ($tenant->file != null) {
//            unlink('file/research/'.$tenant->file);
//        }

        $tenant->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/tenant/UserController.php
<?php

namespace App\Http\Controllers\tenant;

use App\Role;
use App\Tenant;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($subdomain)
    {
        $tenant = Tenant::where('subdomain', $subdomain)->first();

        $users = User::where('tenant_id', $tenant->id)->get();

        $roles = Role::all();

        return view('users.index')
            ->withUsers($users)
            ->withRoles($roles);
    }

    public function usersByRole($subdomain, $role_id)
    {
        $tenant = Tenant::where('subdomain', $subdomain)->first();

        $users = User::where([
            ['role_id', '=', $role_id],
            ['tenant_id', '=', $tenant->id]
        ])->get();

        $roles = Role::all();

        return view('users.index')
            ->withUsers($users)
            ->withRoles($roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store($subdomain, Request $request)
    {
        $this->validate($request, [
            'fullname' => 'required|max:255',
            'ktp_id' => 'required|unique:users',
            'username' => 'required|unique:users',
            'password' => 'required',
            'email' => 'required|unique:users',
            'phone' => 'required|unique:users',
        ]);

        $tenant = Tenant::where('subdomain', $subdomain)->first();

        $user = new User;

        $user->fullname = $request->fullname;
        $user->ktp_id = $request->ktp_id;
        $user->username = $request->username;
        $user->password = Hash::make($request->password);
        $user->email = $request->email;
        $user->birth_date = $request->birth_date;
        $user->phone = $request->phone;
        $user->mobile = $request->mobile;
        $user->mobile2 = $request->mobile2;
        $user->pin_bb = $request->pin_bb;
        $user->notes = $request->notes;

        $user->photo = $request->photo;

        $user->address = $request->address;
        $user->zipcode = $request->zipcode;
        $user->fb = $request->fb;
        $user->tw = $request->tw;
        $user->website = $request->website;
        $user->status = $request->status;
        $user->hobby = $request->hobby;
        $user->reason = $request->reason;

//        Default User Role (Student)
        $user->role_id = 5;

//        Default Branch
        $user->branch_id = 0;

        Log::debug('Tenant ID = ' . $tenant->id);
        $user->tenant_id = $tenant->id;

        $user->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/tenants/index.blade.php
@extends('layouts.main')

@section('content')


    <section class="content-header">
        <h1>
            Daftar Tenant
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="#">
                    <i class="fa fa-dashboard"></i>
                    Dashboard
                </a>
            </li>
            <li class="active">
                <a href="{{ route('tenants.index', $_SERVER['HTTP_HOST']) }}">
                    <i class="fa fa-building"></i>
                    Tenants
                </a>
            </li>
        </ol>
    </section>

    <section class="content">

        <div class="row">

            <div class="modal fade" id="modalAdd">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="defaultModalLabel">Tambah Tenant</h4>
                        </div>

                        <form class="" action="{{ route('tenants.store', $_SERVER['HTTP_HOST']) }}" method="post"
                              data-parsley-validate>

                            <div class="modal-body">
                                <fieldset>
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label> Nama : </label>
                                            <input type="text" name="name" class="form-control" required>
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label> Deskripsi : </label>
                                            <textarea type="text" name="description" class="form-control"
                                                      rows="4"></textarea>
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label> Tipe Host : </label>
                                            <input type="radio" name="is_cname" value="1" onclick="customDomain()"
                                                   checked>
                                            Domain
                                            <input type="radio" name="is_cname" value="0" onclick="customSubdomain()">
                                            Subdomain
                                        </div>
                                    </div>

                                    <div id="domain" class="col-md-6">
                                        <div class="form-group">
                                            <label> Domain : </label>
                                            <input type="text" name="domain" class="form-control" maxlength="25">
                                        </div>
                                    </div>

                                    <div id="subdomain" class="col-md-6">
                                        <div class="form-group">
                                            <label> Subdomain : </label>
                                            <input type="text" name="subdomain" class="form-control"
                                                   maxlength="10">
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label> Logo Perusahaan : </label>
                                            <input type="file" name="company_logo">
                                        </div>
                                    </div>

                                </fieldset>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">
                                    <i
                                            class="fa fa-close"></i>
                                    Tutup
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-save"></i>
                                    Simpan
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>


            <div class="col-xs-12">

                @foreach ($errors->all() as $error)
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                        {{ $error }}
                    </div>
                @endforeach

                @include('layouts.partials.message')

                <div class="box box-primary">
                    <div class="box-header">
                        <a class="btn btn-info pull-left col-md-1" href="#!" data-toggle="modal"
                           data-target="#modalAdd">
                            <span class="fa fa-plus"></span>
                        </a>

                    </div>
                    <div class="box-body">
                        <table class="table js-basic-example dataTable">
                            <thead>
                            <tr>
                                <th>Nama Tenant</th>
                                <th>DNS</th>
                                <th>Deskripsi</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($tenants as $tenant)
                                @if($tenant->id != 1)
                                    <tr>
                                        <td><b>{{ $tenant->name }}</b></td>
                                        <td>
                                            @if($tenant->is_cname)
                                                <i>{{ $tenant->domain }}</i>
                                                <a href="http://{{ $tenant->domain }}" target="_blank">
                                                    <i class="fa fa-link"></i>
                                                </a>
                                            @else
                                                <i>{{ $tenant->subdomain . '.' . env('HOST_NAME') }}</i>
                                                <a href="http://{{ $tenant->subdomain . '.' . env('HOST_NAME') }}"
                                                   target="_blank">
                                                    <i class="fa fa-link"></i>
                                                </a>
                                            @endif
                                        </td>
                                        <td>{{ $tenant->description }}</td>
                                        <td class="text-right">
                                            <a href="{{ route('tenants.show', [$_SERVER['HTTP_HOST'], $tenant->id]) }}"
                                               class="btn btn-info btn-xs">
                                                <i class="fa fa-search"></i>
                                                Detail
                                            </a>

                                            <a href="{{ route('tenants.edit', [$_SERVER['HTTP_HOST'], $tenant->id]) }}"
                                               class="btn btn-default btn-xs">
                                                <i class="fa fa-edit"></i>
                                                Edit
                                            </a>

                                            <a href="#!" data-toggle="modal" data-target="#modalDelete{{ $tenant->id }}"
                                               class="btn btn-danger btn-xs">
                                                <i class="fa fa-trash"></i>
                                                Hapus
                                            </a>
                                        </td>
                                    </tr>

                                    <div class="modal fade" id="modalDelete{{ $tenant->id }}">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" id="defaultModalLabel">
                                                        Hapus {{ $tenant->name }}
                                                        ?</h4>
                                                </div>
                                                <div class="modal-body">
                                                    Anda yakin ingin menghapus data ini?
                                                </div>
                                                <div class="modal-footer">
                                                    {!! Form::open(['route' => ['tenants.destroy', $_SERVER['HTTP_HOST'], $tenant->id], 'method' => 'DELETE']) !!}
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">
                                                        Batal
                                                    </button>
                                                    <button type="submit" class="btn btn-danger"> Hapus</button>
                                                    {!! Form::close() !!}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endif
                            @endforeach
                            </tbody>
                        </table>

                    </div>

                </div>

            </div>
        </div>

    </section>

@endsection

@section('script')
    <script>
        customDomain();

        function customDomain() {
            document.getElementById('subdomain').style.display = 'none';
            document.getElementById('domain').style.display = 'block';
        }

        function customSubdomain() {
            document.getElementById('subdomain').style.display = 'block';
            document.getElementById('domain').style.display = 'none';
        }
    </script>
@endsection

resources/views/tenants/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Baba Studio</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">

    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">

    <link rel="stylesheet" href="/plugins/iCheck/flat/blue.css">

    <link rel="stylesheet" href="/plugins/morris/morris.css">

    <link rel="stylesheet" href="/plugins/jvectormap/jquery-jvectormap-1.2.2.css">

    <link rel="stylesheet" href="/plugins/datepicker/datepicker3.css">

    <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">

    <link rel="stylesheet" href="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

    <link href="/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css">

    <link rel="stylesheet" href="/css/froala_editor.min.css">

    <link rel="stylesheet" href="/css/froala_style.min.css">


    @yield('style')
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#!"><b>{{ $tenant->name }}</b></a>
    </div>
    <div class="login-box-body">
        <form method="POST" action="{{ route('tenant.login', $tenant->subdomain) }}">
            {{ csrf_field() }}
            <div class="form-group has-feedback">
                <input name="email" type="email" class="form-control" placeholder="Email">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                @if ($errors->has('email'))
                    <span class="help-block">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
                @endif
            </div>
            <div class="form-group has-feedback">
                <input name="password" type="password" class="form-control" placeholder="Password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <!-- /.col -->
                <div class="col-md-7">
                    <a href="{{ route('register') }}" class="pull-left">Daftar Baru</a><br>
                    <a href="#" class="pull-left">Lupa password ?</a><br>
                </div>
                <div class="col-md-5">
                    <button type="submit" class="btn btn-info btn-block btn-flat pull-right">Masuk</button>
                </div>
                <!-- /.col -->
            </div>
        </form>
    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
<!-- jQuery 2.2.3 -->
<script src="/plugins/jQuery/jquery-2.2.3.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<script src="/plugins/fastclick/fastclick.js"></script>
<script src="/dist/js/app.min.js"></script>
<script src="/dist/js/demo.js"></script>
<script src="/js/parsley.min.js"></script>
<script src="/js/dropzone.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>

<script src="/plugins/jquery-datatable/jquery-datatable.js"></script>

<script src="/plugins/jquery-datatable/jquery.dataTables.js"></script>
<script src="/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>

<script type="text/javascript">
    var baseUrl = "{{ url('/') }}";
</script>
<script src="/plugins/light-gallery/js/lightgallery-all.js"></script>

<script src="/js/image-gallery.js"></script>

<script src="/js/select2.min.js"></script>

<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>


<script type="text/javascript">
    $('.select2-multi').select2();
</script>
<script type="text/javascript">
    $('.datepicker').datepicker({
        format: 'yyyy/mm/dd'
    });
</script>
</body>
</html>