routes/web.php
<?php

Route::get('noPermission', 'DashboardController@noPermission')->name('noPermission');

Route::post('register', 'Auth\RegisterController@register');

Route::get('register', 'HomeController@register')->name('register');

Route::get('frontend', 'HomeController@index');

/* Tenant Routes */
Route::group(array(
    'domain' => '{subdomain}.' . env('HOST_NAME'),
    'as' => 'tenant.',
    'middleware' => 'multisubdomain'
), (function () {

    /* Auth Routes*/
    Route::get('/', [
        'as' => 'landing',
        'uses' => 'LoginController@getTenantLogin'
    ]);

    Route::post('login', [
        'as' => 'login',
        'uses' => 'LoginController@tenantLogin'
    ]);

    Route::group(['middleware' => ['authen.tenant']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@tenantLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@tenantDashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::put('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::put('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::resource('users', 'tenant\UserController');

        Route::resource('roles', 'RoleController');

        Route::resource('courses', 'CourseController');

    });
    /* End Auth Routes*/

}));
/* end Tenant Routes */

Route::group(array('domain' => '{domain}'), (function () {

    Route::get('/', [
        'as' => '/',
        'uses' => 'LoginController@getLogin',
        'middleware' => 'multidomain'
    ]);

    Route::post('login', [
        'as' => 'login',
        'uses' => 'LoginController@postLogin'
    ]);

    Route::group(['middleware' => ['authen']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@getLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@dashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me.edit',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::get('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::get('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        /* My Tenant */

        Route::get('tenants/me', [
            'as' => 'tenants.me',
            'uses' => 'TenantController@me'
        ]);

        Route::get('tenants/me/edit', [
            'as' => 'tenants.me.edit',
            'uses' => 'TenantController@meEdit'
        ]);

        Route::get('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpertPage',
            'uses' => 'TenantController@selectExpertPage'
        ]);

        Route::post('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpert',
            'uses' => 'TenantController@selectExpert'
        ]);

        Route::post('tenants/{id}/unselect-expert', [
            'as' => 'tenants.unselectExpert',
            'uses' => 'TenantController@unselectExpert'
        ]);

        /* End My Tenant */

        Route::resource('tenants', 'TenantController');

        Route::resource('categories', 'CategoryController');

        Route::resource('sub_categories', 'SubCategoryController');

        Route::resource('users', 'UserController');

        Route::resource('roles', 'RoleController');

        Route::resource('courses', 'CourseController');

        Route::get('users/role/{id}', [
            'as' => 'users.role',
            'uses' => 'UserController@usersByRole'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::post('users/select-expert', 'UserController@selectExpert')->name('users.selectExpert');

    });

}));


Route::get('/home', 'HomeController@index')->name('home');

Route::post('/users/add-role', 'UserController@addRole');

Route::post('/users/delete-role', 'UserController@deleteRole');

Route::get('404', [
    'as' => 'notfound',
    'uses' => 'HomeController@notfound'
]);

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 1.0.0
  </div>
  <strong>Copyright &copy; 2017 <a href="#!"></a>.</strong> All rights
  reserved.
</footer>

resources/views/layouts/partials/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="#!" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>BS</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Baba Studio</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul class="menu">
                                <li><!-- start message -->
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="../../dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                                <!-- end message -->
                            </ul>
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li>

            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/partials/message.blade.php
@if(Session::has('success'))
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
        {{ Session::get('success') }}
    </div>
@endif

resources/views/layouts/partials/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <div class="user-panel">
            <div class="pull-left image">
                <img src="/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->fullname }}</p>
                <a>
                    <i class="fa fa-circle text-success"></i>
                    Online
                </a>
            </div>
        </div>

        {{-- Multi Domain --}}
        @if(true)
            <ul class="sidebar-menu">
                <li>
                    <a href="{{ route('dashboard', '') }}">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li class="header"> Kelola User</li>
                <li>
                    <a href="{{ route('roles.index', '') }}">
                        <i class="fa fa-key"></i>
                        <span>Roles</span>
                    </a>
                </li>
                <li class="active treeview">
                    <a href="#">
                        <i class="fa fa-users"></i>
                        <span>User</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{{ route('users.index', '') }}">
                                <i class="fa fa-circle-o"></i>
                                Semua
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('users.role', [$_SERVER['HTTP_HOST'], 1]) }}">
                                <i class="fa fa-circle-o"></i>
                                SuperAdmin
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.role', [$_SERVER['HTTP_HOST'], 2]) }}">
                                <i class="fa fa-circle-o"></i>
                                Management
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.role', [$_SERVER['HTTP_HOST'], 3]) }}">
                                <i class="fa fa-circle-o"></i>
                                Expert
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.role', [$_SERVER['HTTP_HOST'], 4]) }}">
                                <i class="fa fa-circle-o"></i>
                                Instructor
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.role', [$_SERVER['HTTP_HOST'], 5]) }}">
                                <i class="fa fa-circle-o"></i>
                                Student
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="header"> Kursus</li>
                <li class="active treeview">
                    <a href="#">
                        <i class="fa fa-book"></i>
                        <span> Kursus</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{{ route('courses.index', $_SERVER['HTTP_HOST']) }}">
                                <i class="fa fa-circle-o"></i>
                                Kursus
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('categories.index', $_SERVER['HTTP_HOST']) }}">
                                <i class="fa fa-circle-o"></i>
                                Kategori
                            </a>
                        </li>
                    </ul>
                </li>

                @if(Auth::user()->role_id === 3)
                    <li class="header"> Kelola Tenant</li>
                    <li>
                        <a href="{{ route('tenants.me', $_SERVER['HTTP_HOST']) }}">
                            <i class="fa fa-building"></i>
                            <span> Kelola Tenant</span>
                        </a>
                    </li>
                @endif

                @if($_SERVER['HTTP_HOST'] === env('HOST_NAME'))
                    <li class="header"> Tenant</li>
                    <li>
                        <a href="{{ route('tenants.index', $_SERVER['HTTP_HOST']) }}">
                            <i class="fa fa-building"></i>
                            <span> Daftar Tenant</span>
                        </a>
                    </li>
                @endif

                <li class="header"> Pengaturan</li>
                <li class="active treeview">
                    <a href="#">
                        <i class="fa fa-gear"></i>
                        <span> Pengaturan</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{{ route('me', $_SERVER['HTTP_HOST']) }}">
                                <i class="fa fa-circle-o"></i>
                                Profil
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-circle-o"></i>
                                Ubah Kata Sandi
                            </a>
                        </li>

                    </ul>
                </li>

                <form id="logout"
                      action="{{ !Auth::user()->tenant->is_cname ? route('tenant.logout', Auth::user()->tenant->subdomain) : route('logout', $_SERVER['HTTP_HOST']) }}"
                      method="post">
                    {{ csrf_field() }}
                </form>

                <li>
                    <a href="#" onclick="event.preventDefault(); document.getElementById('logout').submit();">
                        <i class="fa fa-sign-out"></i>
                        <span> Keluar</span>
                    </a>
                </li>
            </ul>
        @endif
        {{-- Multi Domain --}}

        {{-- Multi Subdomain --}}
        @if(false)
            <ul class="sidebar-menu">
                <li class="header"> User Management</li>
                <li>
                    <a href="{{ url('dashboard') }}">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li class="header"> User Management</li>
                <li>
                    <a href="{{ route('roles.index') }}">
                        <i class="fa fa-key"></i>
                        <span>Roles</span>
                    </a>
                </li>
                <li class="active treeview">
                    <a href="#">
                        <i class="fa fa-users"></i>
                        <span>Users</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{{ route('users.index') }}">
                                <i class="fa fa-circle-o"></i>
                                Semua
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('users.role', 1) }}">
                                <i class="fa fa-circle-o"></i>
                                SuperAdmin
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.role', 2) }}">
                                <i class="fa fa-circle-o"></i>
                                Management
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.role', 3) }}">
                                <i class="fa fa-circle-o"></i>
                                Expert
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.role', 4) }}">
                                <i class="fa fa-circle-o"></i>
                                Instructor
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.role', 5) }}">
                                <i class="fa fa-circle-o"></i>
                                Student
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="header"> Kursus</li>
                <li class="active treeview">
                    <a href="#">
                        <i class="fa fa-book"></i>
                        <span> Kursus</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{{ url('courses') }}">
                                <i class="fa fa-circle-o"></i>
                                Kursus
                            </a>
                        </li>
                        <li>
                            <a href="{{ url('categories') }}">
                                <i class="fa fa-circle-o"></i>
                                Kategori
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="header"> Tenants</li>
                <li>
                    <a href="{{ url('tenants') }}">
                        <i class="fa fa-building"></i>
                        <span> Tenants</span>
                    </a>
                </li>
            </ul>
    @endif
    {{-- Multi Subdomain --}}



    <!-- <li class="treeview">
        <a href="#">
          <i class="fa fa-pie-chart"></i>
          <span>Charts</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="pages/charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
          <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
          <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
          <li><a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
        </ul>
      </li> -->


        <!-- <li><a href="documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
        <li class="header">LABELS</li>
        <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li> -->
    </section>
</aside>