routes/web.php
<?php

Route::get('noPermission', 'DashboardController@noPermission')->name('noPermission');

Route::post('register', 'Auth\RegisterController@register');

Route::get('register', 'HomeController@register')->name('register');

Route::get('frontend', 'HomeController@index');

/* Tenant Routes */
Route::group(array(
    'domain' => '{subdomain}.' . env('HOST_NAME'),
    'as' => 'tenant.',
    'middleware' => 'multisubdomain'
), (function () {

    /* Auth Routes*/
    Route::get('/', [
        'as' => 'landing',
        'uses' => 'LoginController@getTenantLogin'
    ]);

    Route::post('login', [
        'as' => 'login',
        'uses' => 'LoginController@tenantLogin'
    ]);

    Route::group(['middleware' => ['authen.tenant']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@tenantLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@tenantDashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::put('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::put('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::resource('users', 'tenant\UserController');

        Route::resource('roles', 'RoleController');

        Route::resource('courses', 'CourseController');

    });
    /* End Auth Routes*/

}));
/* end Tenant Routes */

Route::group(array('domain' => '{domain}'), (function () {

    Route::get('/', [
        'as' => '/',
        'uses' => 'LoginController@getLogin',
        'middleware' => 'multidomain'
    ]);

    Route::post('login', [
        'as' => 'login',
        'uses' => 'LoginController@postLogin'
    ]);

    Route::group(['middleware' => ['authen']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@getLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@dashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me.edit',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::get('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::get('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        /* My Tenant */

        Route::get('tenants/me', [
            'as' => 'tenants.me',
            'uses' => 'TenantController@me'
        ]);

        Route::get('tenants/me/edit', [
            'as' => 'tenants.me.edit',
            'uses' => 'TenantController@meEdit'
        ]);

        Route::get('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpertPage',
            'uses' => 'TenantController@selectExpertPage'
        ]);

        Route::post('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpert',
            'uses' => 'TenantController@selectExpert'
        ]);

        Route::post('tenants/{id}/unselect-expert', [
            'as' => 'tenants.unselectExpert',
            'uses' => 'TenantController@unselectExpert'
        ]);

        /* End My Tenant */

        Route::resource('tenants', 'TenantController');

        Route::resource('categories', 'CategoryController');

        Route::resource('sub_categories', 'SubCategoryController');

        Route::resource('users', 'UserController');

        Route::resource('roles', 'RoleController');

        Route::resource('courses', 'CourseController');

        Route::get('users/role/{id}', [
            'as' => 'users.role',
            'uses' => 'UserController@usersByRole'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::post('users/select-expert', 'UserController@selectExpert')->name('users.selectExpert');

    });

}));


Route::get('/home', 'HomeController@index')->name('home');

Route::post('/users/add-role', 'UserController@addRole');

Route::post('/users/delete-role', 'UserController@deleteRole');

Route::get('404', [
    'as' => 'notfound',
    'uses' => 'HomeController@notfound'
]);

resources/views/courses/index.blade.php
@extends('layouts.main')

@section('content')

    <div class="row">

        <div class="modal fade" id="modalAdd">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="defaultModalLabel">Tambah Bab</h4>
                    </div>

                    <form action="{{ route('courses.store', $_SERVER['HTTP_HOST']) }}" method="post" data-parsley-validate>

                        <div class="modal-body">
                            <fieldset>
                                {{ csrf_field() }}
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Judul : </label>
                                        <input class="form-control" type="text" name="title">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label> Deskripsi : </label>
                                        <textarea class="form-control" name="description" rows="3"></textarea>
                                    </div>
                                </div>

                                <div class="col-md-8">
                                    <div class="form-group">
                                        <label> Kategori : </label>
                                        <select class="form-control" name="category_id">
                                            @foreach($categories as $category)
                                                <option value="{{ $category->id }}"> {{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label> Harga (Rp) : </label>
                                        <input class="form-control" type="number" name="price">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <label> Daftar Bab : </label>
                                    <br>
                                    <button type="button" class="btn btn-default" href="#!" data-toggle="modal"
                                            data-target="#modalAddSection"><i class="fa fa-plus"></i> Tambah Bab
                                    </button>
                                </div>

                            </fieldset>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal"><i
                                        class="fa fa-close"></i> Tutup
                            </button>
                            <button type="submit" class="btn btn-primary" onclick="addSection()"><i
                                        class="fa fa-save"></i> Simpan
                            </button>
                        </div>

                    </form>
                </div>
            </div>
        </div>

        <div class="col-xs-12">

            @include('layouts.partials.message')

            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Daftar Kursus</h3>
                    <br>
                    <a class="btn btn-info pull-left col-md-1" href="{{ route('courses.create', $_SERVER['HTTP_HOST']) }}">
                        <span class="fa fa-plus"></span>
                    </a>

                </div>
                <div class="box-body">
                    <table class="table js-basic-example dataTable">
                        <thead>
                        <tr>
                            <th>Judul</th>
                            <th>Durasi</th>
                            <th>Harga (Rp)</th>
                            <th>Instruktur</th>
                            <th>Status</th>
                            <th>##</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($courses as $course)
                            <tr>
                                <td><b>{{ substr($course->title, 0, 20) }}</b></td>
                                <td class="text-green">{{ $course->duration }} Menit</td>
                                <td>Rp. {{ number_format($course->price, 0, ',', '.') }}</td>
                                <td>{{ \App\User::find($course->author_id)->fullname }}</td>
                                <td class="text-green">{{ $course->status }}</td>
                                <td class="text-right">

                                    <a href="#!" class="btn btn-info btn-xs">
                                        <i class="fa fa-users"></i> Murid</a>

                                    <a href="#!" class="btn btn-default btn-xs">
                                        <i class="fa fa-gear"></i> Kelola</a>

                                    <a href="#!" data-toggle="modal" data-target="#modalDelete{{ $course->id }}"
                                       class="btn btn-danger btn-xs"><i class="fa fa-trash"></i> Hapus</a>
                                </td>
                            </tr>

                            <div class="modal fade" id="modalDelete{{ $course->id }}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="defaultModalLabel">Hapus {{ $course->name }}
                                                ?</h4>
                                        </div>
                                        <div class="modal-body">
                                            Anda yakin ingin menghapus data ini?
                                        </div>
                                        <div class="modal-footer">
                                            {!! Form::open(['route' => ['courses.destroy', $course->id], 'method' => 'DELETE']) !!}
                                            <button type="button" class="btn btn-default" data-dismiss="modal"> Batal
                                            </button>
                                            <button type="submit" class="btn btn-danger"> Hapus</button>
                                            {!! Form::close() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                        </tbody>
                    </table>

                </div>

            </div>

        </div>
    </div>

@endsection

resources/views/courses/student.blade.php
@extends('layouts.main')

@section('content')

    <div class="row">

        <div class="col-xs-12">

            @include('layouts.partials.message')

            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Daftar Kursus</h3>
                    <br>
                    <a class="btn btn-info pull-left col-md-1" href="{{ route('courses.create') }}">
                        <span class="fa fa-plus"></span>
                    </a>

                </div>
                <div class="box-body">
                    <table class="table js-basic-example dataTable">
                        <thead>
                        <tr>
                            <th>Judul</th>
                            <th>Durasi</th>
                            <th>Harga (Rp)</th>
                            <th>Instruktur</th>
                            <th>Status</th>
                            <th>##</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($courses as $course)
                            <tr>
                                <td><b>{{ substr($course->title, 0, 20) }}</b></td>
                                <td class="text-green">{{ $course->duration }} Menit</td>
                                <td>Rp. {{ number_format($course->price, 0, ',', '.') }}</td>
                                <td>{{ \App\User::find($course->author_id)->fullname }}</td>
                                <td class="text-green">{{ $course->status }}</td>
                                <td class="text-right">

                                    <a href="#!" class="btn btn-info btn-xs">
                                        <i class="fa fa-users"></i> Murid</a>

                                    <a href="#!" class="btn btn-default btn-xs">
                                        <i class="fa fa-gear"></i> Kelola</a>

                                    <a href="#!" data-toggle="modal" data-target="#modalDelete{{ $course->id }}"
                                       class="btn btn-danger btn-xs"><i class="fa fa-trash"></i> Hapus</a>
                                </td>
                            </tr>

                            <div class="modal fade" id="modalDelete{{ $course->id }}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="defaultModalLabel">Hapus {{ $course->name }}
                                                ?</h4>
                                        </div>
                                        <div class="modal-body">
                                            Anda yakin ingin menghapus data ini?
                                        </div>
                                        <div class="modal-footer">
                                            {!! Form::open(['route' => ['courses.destroy', $course->id], 'method' => 'DELETE']) !!}
                                            <button type="button" class="btn btn-default" data-dismiss="modal"> Batal
                                            </button>
                                            <button type="submit" class="btn btn-danger"> Hapus</button>
                                            {!! Form::close() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                        </tbody>
                    </table>

                </div>

            </div>

        </div>
    </div>

@endsection