routes/web.php
<?php

Route::get('noPermission', 'DashboardController@noPermission')->name('noPermission');

Route::post('register', 'Auth\RegisterController@register');

Route::get('register', 'HomeController@register')->name('register');

Route::get('frontend', 'HomeController@index');

/* Tenant Routes */
Route::group(array(
    'domain' => '{subdomain}.' . env('HOST_NAME'),
    'as' => 'tenant.',
    'middleware' => 'multisubdomain'
), (function () {

    /* Auth Routes*/
    Route::get('/', [
        'as' => 'landing',
        'uses' => 'LoginController@getTenantLogin'
    ]);

    Route::post('/login', [
        'as' => 'login',
        'uses' => 'LoginController@tenantLogin'
    ]);

    Route::group(['middleware' => ['authen.tenant']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@tenantLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@dashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me.edit',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::put('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::put('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        /* My Tenant */

        Route::get('tenants/me', [
            'as' => 'tenants.me',
            'uses' => 'TenantController@me'
        ]);

        Route::get('tenants/me/edit', [
            'as' => 'tenants.me.edit',
            'uses' => 'TenantController@meEdit'
        ]);

        Route::get('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpertPage',
            'uses' => 'TenantController@selectExpertPage'
        ]);

        Route::post('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpert',
            'uses' => 'TenantController@selectExpert'
        ]);

        Route::post('tenants/{id}/unselect-expert', [
            'as' => 'tenants.unselectExpert',
            'uses' => 'TenantController@unselectExpert'
        ]);

        /* End My Tenant */

        Route::resource('tenants', 'tenant\TenantController');

        Route::resource('categories', 'tenant\CategoryController');

        Route::resource('sub_categories', 'tenant\SubCategoryController');

        Route::resource('users', 'tenant\UserController');

        Route::resource('roles', 'tenant\RoleController');

        Route::resource('sections', 'tenant\SectionController');

        Route::post('courses/{id}/section', [
            'as' => 'courses.add.section',
            'uses' => 'SectionController@store'
        ]);

        Route::resource('courses', 'tenant\CourseController');

        Route::get('users/role/{id}', [
            'as' => 'users.role',
            'uses' => 'UserController@usersByRole'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::post('users/select-expert', 'UserController@selectExpert')->name('users.selectExpert');

        Route::delete('sections/delete-all/{id}', [
            'as' => 'sections.delete.all',
            'uses' => 'SectionController@deleteAll'
        ]);

        Route::post('material/store', 'MaterialController@postMaterial');

        Route::delete('material/delete/{id}', 'MaterialController@deleteMaterial');

        Route::resource('quizzes', 'QuizController');

    });
    /* End Auth Routes*/

}));
/* end Tenant Routes */

Route::group(array('domain' => '{domain}'), (function () {

    Route::get('/', [
        'as' => '/',
        'uses' => 'LoginController@getLogin',
        'middleware' => 'multidomain'
    ]);

    Route::post('login', [
        'as' => 'login',
        'uses' => 'LoginController@postLogin'
    ]);

    Route::group(['middleware' => ['authen']], function () {

        Route::post('/logout', [
            'as' => 'logout',
            'uses' => 'LoginController@getLogout'
        ]);

        Route::get('/dashboard', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@dashboard'
        ]);

        Route::get('me', [
            'as' => 'me',
            'uses' => 'ProfileController@index'
        ]);

        Route::get('me/edit', [
            'as' => 'me.edit',
            'uses' => 'ProfileController@edit'
        ]);

        Route::put('me/update', [
            'as' => 'me.update',
            'uses' => 'ProfileController@update'
        ]);

        Route::put('me/update-image', [
            'as' => 'me.update.image',
            'uses' => 'ProfileController@changeImage'
        ]);

        Route::put('me/update-password', [
            'as' => 'me.update.password',
            'uses' => 'ProfileController@changePassword'
        ]);

        /* My Tenant */

        Route::get('tenants/me', [
            'as' => 'tenants.me',
            'uses' => 'TenantController@me'
        ]);

        Route::get('tenants/me/edit', [
            'as' => 'tenants.me.edit',
            'uses' => 'TenantController@meEdit'
        ]);

        Route::get('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpertPage',
            'uses' => 'TenantController@selectExpertPage'
        ]);

        Route::post('tenants/{id}/select-expert', [
            'as' => 'tenants.selectExpert',
            'uses' => 'TenantController@selectExpert'
        ]);

        Route::post('tenants/{id}/unselect-expert', [
            'as' => 'tenants.unselectExpert',
            'uses' => 'TenantController@unselectExpert'
        ]);

        /* End My Tenant */

        Route::resource('tenants', 'TenantController');

        Route::resource('categories', 'CategoryController');

        Route::resource('sub_categories', 'SubCategoryController');

        Route::resource('users', 'UserController');

        Route::resource('roles', 'RoleController');

        Route::resource('sections', 'SectionController');

        Route::post('courses/{id}/section', [
            'as' => 'courses.add.section',
            'uses' => 'SectionController@store'
        ]);

        Route::resource('courses', 'CourseController');

        Route::get('users/role/{id}', [
            'as' => 'users.role',
            'uses' => 'UserController@usersByRole'
        ]);

        Route::put('user/update-role/{id}', [
            'as' => 'changeRole',
            'uses' => 'UserController@changeRole'
        ]);

        Route::post('users/select-expert', 'UserController@selectExpert')->name('users.selectExpert');

        Route::delete('sections/delete-all/{id}', [
            'as' => 'sections.delete.all',
            'uses' => 'SectionController@deleteAll'
        ]);

        Route::post('material/store', 'MaterialController@postMaterial');

        Route::delete('material/delete/{id}', 'MaterialController@deleteMaterial');

        Route::resource('quizzes', 'QuizController');

        // Route::post('quiz/store', 'QuizController@store');


        /* Append File */
//        Route::get('bangke', 'CategoryController@index');
        /* End Append File */
    });

}));


Route::get('/home', 'HomeController@index')->name('home');

Route::post('/users/add-role', 'UserController@addRole');

Route::post('/users/delete-role', 'UserController@deleteRole');

Route::get('404', [
    'as' => 'notfound',
    'uses' => 'HomeController@notfound'
]);

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function users(){
        return $this->hasMany('App\User', 'role_id', 'id');
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use App\Tenant;
use Illuminate\Http\Request;
use App\Role;

class RoleController extends Controller
{
    public function index($domain)
    {
        $roles = Role::all();

        return view('roles.index')->withRoles($roles);
    }

    public function show($domain, $id)
    {
        $tenant = Tenant::where(['domain' => $domain])->first();
        $role = Role::find($id);
        $permission = Permission::where(['role_id' => $role->id, 'tenant_id' => $tenant->id])->first();

        return view('roles.show')
            ->withPermission($permission)
            ->withRole($role);
    }

    public function update($domain, Request $request, $id)
    {
//        dd($request);
        $tenant = Tenant::where(['domain' => $domain])->first();

        $role = Role::find($id);

        $permission = Permission::where(['role_id' => $role->id, 'tenant_id' => $tenant->id])->first();

        if ($permission === null) {
            $permission = new Permission;
        }

        $permission->read_role = $request->read_role != null;
        $permission->update_role = $request->update_role != null;

        $permission->read_user = $request->read_user != null;
        $permission->create_user = $request->create_user != null;
        $permission->update_user = $request->update_user != null;
        $permission->delete_user = $request->delete_user != null;

        $permission->read_course = $request->read_course != null;
        $permission->create_course = $request->create_course != null;
        $permission->update_course = $request->update_course != null;
        $permission->delete_course = $request->delete_course != null;

        $permission->read_category = $request->read_category != null;
        $permission->create_category = $request->create_category != null;
        $permission->update_category = $request->update_category != null;
        $permission->delete_category = $request->delete_category != null;

        $permission->read_tenant = $request->read_tenant != null;
        $permission->create_tenant = $request->create_tenant != null;
        $permission->update_tenant = $request->update_tenant != null;
        $permission->delete_tenant = $request->delete_tenant != null;

        $permission->read_tenant_me = $request->read_tenant_me != null;
        $permission->create_tenant_me = $request->create_tenant_me != null;
        $permission->update_tenant_me = $request->update_tenant_me != null;
        $permission->delete_tenant_me = $request->delete_tenant_me != null;

        $permission->role_id = $role->id;
        $permission->tenant_id = $tenant->id;

        $permission->save();

        return redirect()->route('me', $domain);
    }

}

app/Http/Controllers/tenant/RoleController.php
<?php

namespace App\Http\Controllers\tenant;

use App\Permission;
use App\Tenant;
use Illuminate\Http\Request;
use App\Role;

class RoleController extends Controller
{
    public function index($subdomain)
    {
        $roles = Role::all();

        return view('roles.index')->withRoles($roles);
    }

    public function show($subdomain, $id)
    {
        $tenant = Tenant::where(['subdomain' => $subdomain])->first();
        $role = Role::find($id);
        $permission = Permission::where(['role_id' => $role->id, 'tenant_id' => $tenant->id])->first();

        return view('roles.show')
            ->withPermission($permission)
            ->withRole($role);
    }

    public function update($subdomain, Request $request, $id)
    {
//        dd($request);
        $tenant = Tenant::where(['subdomain' => $subdomain])->first();

        $role = Role::find($id);

        $permission = Permission::where(['role_id' => $role->id, 'tenant_id' => $tenant->id])->first();

        if ($permission === null) {
            $permission = new Permission;
        }

        $permission->read_role = $request->read_role != null;
        $permission->update_role = $request->update_role != null;

        $permission->read_user = $request->read_user != null;
        $permission->create_user = $request->create_user != null;
        $permission->update_user = $request->update_user != null;
        $permission->delete_user = $request->delete_user != null;

        $permission->read_course = $request->read_course != null;
        $permission->create_course = $request->create_course != null;
        $permission->update_course = $request->update_course != null;
        $permission->delete_course = $request->delete_course != null;

        $permission->read_category = $request->read_category != null;
        $permission->create_category = $request->create_category != null;
        $permission->update_category = $request->update_category != null;
        $permission->delete_category = $request->delete_category != null;

        $permission->read_tenant = $request->read_tenant != null;
        $permission->create_tenant = $request->create_tenant != null;
        $permission->update_tenant = $request->update_tenant != null;
        $permission->delete_tenant = $request->delete_tenant != null;

        $permission->read_tenant_me = $request->read_tenant_me != null;
        $permission->create_tenant_me = $request->create_tenant_me != null;
        $permission->update_tenant_me = $request->update_tenant_me != null;
        $permission->delete_tenant_me = $request->delete_tenant_me != null;

        $permission->role_id = $role->id;
        $permission->tenant_id = $tenant->id;

        $permission->save();

        return redirect()->route('me', $subdomain);
    }

}

resources/views/roles/index.blade.php
@extends('layouts.main')

@section('content')

    <div class="row">

        <div class="modal fade" id="modalAdd">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="defaultModalLabel">Tambah Peran</h4>
                    </div>
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>


        <div class="col-xs-12">


            <div class="box box-primary">
                <div class="box-body">
                    <table class="table js-basic-example dataTable">
                        <thead>
                        <tr>
                            <th>Nama</th>
                            <th>Deskripsi</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($roles as $role)
                            <tr>
                                <td>{{ $role->name }}</td>
                                <td>{{ $role->description }}</td>
                                <td class="text-right">
                                    <a href="{{ route('roles.show', [$_SERVER['HTTP_HOST'], $role->id]) }}"
                                       class="btn btn-default btn-xs">
                                        <i class="fa fa-gear"></i>
                                        Kelola
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                </div>

            </div>

        </div>
    </div>

@endsection

resources/views/roles/show.blade.php
@extends('layouts.main')

@section('content')

{{-- @php
$permission = new App\Permission;
@endphp --}}
    <section class="content-header">
        <h1>
            Kelola {{ $role->name }}
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="#">
                    <i class="fa fa-dashboard"></i>
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{{ route('tenants.index', $_SERVER['HTTP_HOST']) }}">
                    <i class="fa fa-building"></i>
                    Tenants
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-key"></i>
                    {{ $role->name }}
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-gear"></i>
                    Kelola
                </a>
            </li>
        </ol>
    </section>

    @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach

    <section class="content">

        <div class="row">

            <div class="col-xs-12">

                @include('layouts.partials.message')

{{--                @if($permission != null)--}}
                    <div class="box box-primary">
                        <form class="" action="{{ route('roles.update', [$_SERVER['HTTP_HOST'], $role->id]) }}"
                              method="post"
                              data-parsley-validate>

                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input name="_method" type="hidden" value="PUT">

                            <div class="box-body">
                                <div class="col-md-12">

                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>Menu</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td></td>
                                            <td class="text-right"><label><input id="all" name="all" type="checkbox">
                                                    Semua</label></td>
                                        </tr>
                                        <tr>
                                            <td><b>Role</b></td>
                                            <td class="text-right">
                                                <label><input name="read_role"
                                                              type="checkbox" {{ $permission->read_role ? 'checked' : '' }}>
                                                    Read</label>
                                                &nbsp;
                                                <label><input name="update_role"
                                                              type="checkbox" {{ $permission->update_role ? 'checked' : '' }}>
                                                    Update</label>

                                            </td>
                                        </tr>

                                        <tr>
                                            <td><b>User</b></td>
                                            <td class="text-right">
                                                <label><input name="read_user"
                                                              type="checkbox" {{ $permission->read_user ? 'checked' : '' }}>
                                                    Read</label>
                                                &nbsp;
                                                <label><input name="create_user"
                                                              type="checkbox" {{ $permission->create_user ? 'checked' : '' }}>
                                                    Create</label>
                                                &nbsp;
                                                <label><input name="update_user"
                                                              type="checkbox" {{ $permission->update_user ? 'checked' : '' }}>
                                                    Update</label>
                                                &nbsp;
                                                <label><input name="delete_user"
                                                              type="checkbox" {{ $permission->delete_user ? 'checked' : '' }}>
                                                    Delete</label>

                                            </td>
                                        </tr>

                                        <tr>
                                            <td><b>Kursus</b></td>
                                            <td class="text-right">
                                                <label><input name="read_course"
                                                              type="checkbox" {{ $permission->read_course ? 'checked' : '' }}>
                                                    Read</label>
                                                &nbsp;
                                                <label><input name="create_course"
                                                              type="checkbox" {{ $permission->create_course ? 'checked' : '' }}>
                                                    Create</label>
                                                &nbsp;
                                                <label><input name="update_course"
                                                              type="checkbox" {{ $permission->update_course ? 'checked' : '' }}>
                                                    Update</label>
                                                &nbsp;
                                                <label><input name="delete_course"
                                                              type="checkbox" {{ $permission->delete_course ? 'checked' : '' }}>
                                                    Delete</label>

                                            </td>
                                        </tr>

                                        <tr>
                                            <td><b>Kategori</b></td>
                                            <td class="text-right">
                                                <label><input name="read_category"
                                                              type="checkbox" {{ $permission->read_category ? 'checked' : '' }}>
                                                    Read</label>
                                                &nbsp;
                                                <label><input name="create_category"
                                                              type="checkbox" {{ $permission->create_category ? 'checked' : '' }}>
                                                    Create</label>
                                                &nbsp;
                                                <label><input name="update_category"
                                                              type="checkbox" {{ $permission->update_category ? 'checked' : '' }}>
                                                    Update</label>
                                                &nbsp;
                                                <label><input name="delete_category"
                                                              type="checkbox" {{ $permission->delete_category ? 'checked' : '' }}>
                                                    Delete</label>

                                            </td>
                                        </tr>

                                        <tr>
                                            <td><b>Daftar Tenant</b></td>
                                            <td class="text-right">
                                                <label><input name="read_tenant"
                                                              type="checkbox" {{ $permission->read_tenant ? 'checked' : '' }}>
                                                    Read</label>
                                                &nbsp;
                                                <label><input name="create_tenant"
                                                              type="checkbox" {{ $permission->create_tenant ? 'checked' : '' }}>
                                                    Create</label>
                                                &nbsp;
                                                <label><input name="update_tenant"
                                                              type="checkbox" {{ $permission->update_tenant ? 'checked' : '' }}>
                                                    Update</label>
                                                &nbsp;
                                                <label><input name="delete_tenant"
                                                              type="checkbox" {{ $permission->delete_tenant ? 'checked' : '' }}>
                                                    Delete</label>

                                            </td>
                                        </tr>

                                        <tr>
                                            <td><b>Kelola Tenant</b></td>
                                            <td class="text-right">
                                                <label><input name="read_tenant_me"
                                                              type="checkbox" {{ $permission->read_tenant_me ? 'checked' : '' }}>
                                                    Read</label>
                                                &nbsp;
                                                <label><input name="create_tenant_me"
                                                              type="checkbox" {{ $permission->create_tenant_me ? 'checked' : '' }}>
                                                    Create</label>
                                                &nbsp;
                                                <label><input name="update_tenant_me"
                                                              type="checkbox" {{ $permission->update_tenant_me ? 'checked' : '' }}>
                                                    Update</label>
                                                &nbsp;
                                                <label><input name="delete_tenant_me"
                                                              type="checkbox" {{ $permission->delete_tenant_me ? 'checked' : '' }}>
                                                    Delete</label>

                                            </td>
                                        </tr>

                                        </tbody>
                                    </table>
                                </div>

                            </div>

                            <div class="box-footer">
                                <div class="col-md-12 text-right">
                                    <a class="btn btn-default"
                                       href="{{ route('roles.index', $_SERVER['HTTP_HOST']) }}">
                                        <i class="fa fa-close"></i>
                                        Tutup
                                    </a>

                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-save"></i>
                                        Simpan
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>

                {{--@endif--}}

            </div>
        </div>

    </section>

@endsection

@section('script')

    <script>
        $(function () {
            /* Select All */
            $('#all').change(function () {
                $("input:checkbox").prop('checked', this.checked);
            });
        });
    </script>
    <script>
        @if ($role->is_cname)
        customDomain();
        @else
        customSubdomain();

        @endif

        function customDomain() {
            document.getElementById('subdomain').style.display = 'none';
            document.getElementById('domain').style.display = 'block';
        }

        function customSubdomain() {
            document.getElementById('subdomain').style.display = 'block';
            document.getElementById('domain').style.display = 'none';
        }

    </script>
@endsection